# Generated by Django 6.0.4 on 2026-04-17 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(choices=[('Orchestrator', 'Orchestrator'), ('Scribe', 'Scribe'), ('Scheduler', 'Scheduler'), ('Service Agent', 'Service Agent'), ('Chat', 'Chat')], max_length=50)),
                ('task_label', models.CharField(blank=True, max_length=100)),
                ('action', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
