# Generated by Django 6.0.4 on 2026-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('advisor_name', models.CharField(default='Vlad Donets', max_length=200)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('email_signature', models.TextField(blank=True, default='Vlad Donets\nSolera Financial Advisory')),
                ('meeting_cap', models.IntegerField(default=15)),
                ('ai_provider', models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI GPT')], default='anthropic', max_length=20)),
                ('ai_model', models.CharField(default='claude-sonnet-4-6', max_length=100)),
                ('toggle_email_summary', models.BooleanField(default=True)),
                ('toggle_email_followup', models.BooleanField(default=True)),
                ('toggle_reminder_48hr', models.BooleanField(default=True)),
                ('toggle_reminder_24hr', models.BooleanField(default=True)),
                ('toggle_wealthbox_task', models.BooleanField(default=True)),
                ('toggle_form_draft', models.BooleanField(default=True)),
                ('toggle_weekly_summary', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advisor Settings',
                'verbose_name_plural': 'Advisor Settings',
            },
        ),
    ]
