# Generated by Django 6.0.4 on 2026-04-17 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_label', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(choices=[('email_followup', 'Client Follow-Up Email'), ('email_summary', 'Post-Meeting Summary'), ('reminder_48hr', '48hr Reminder'), ('reminder_24hr', '24hr Reminder'), ('wealthbox_task', 'Wealthbox Tasks'), ('questionnaire_link', 'Questionnaire Link'), ('form', 'Form Draft')], max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('draft_content', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('outlook_message_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
