# Generated by Django 6.0.4 on 2026-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalitem',
            name='item_type',
            field=models.CharField(choices=[('email_followup', 'Client Follow-Up Email'), ('email_summary', 'Post-Meeting Summary'), ('reminder_48hr', '48hr Reminder'), ('reminder_24hr', '24hr Reminder'), ('action_items', 'Action Items'), ('meeting_notes', 'Meeting Notes'), ('calendar_event', 'Calendar Event'), ('questionnaire_link', 'Questionnaire Link'), ('form', 'Form Draft')], max_length=30),
        ),
    ]
