# Generated by Django 6.0.4 on 2026-04-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_new_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
