# Generated by Django 6.0.4 on 2026-04-17 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireToken',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_tokens', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_submissions', to='clients.client')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='questionnaires.questionnairetoken')),
            ],
        ),
    ]
