# Generated by Django 6.0.4 on 2026-04-22 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_task_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWikiArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_type', models.CharField(choices=[('leap_position', 'LEAP Position'), ('life_insurance', 'Life Insurance'), ('investment_accounts', 'Investment Accounts'), ('annual_review', 'Annual Review'), ('client_background', 'Client Background'), ('meeting_history', 'Meeting History'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('source_files', models.JSONField(default=list)),
                ('document_year', models.IntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_articles', to='clients.client')),
            ],
            options={
                'ordering': ['-document_year', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ClientWikiIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_index', to='clients.client')),
            ],
        ),
    ]
