# Generated by Django 6.0.4 on 2026-04-17 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tree_json', models.JSONField(blank=True, null=True)),
                ('build_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('pdf_image', 'PDF (Image/Scanned)'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('txt', 'Plain Text'), ('transcript', 'Meeting Transcript'), ('other', 'Other')], default='other', max_length=20)),
                ('size_kb', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='vlad', max_length=100)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
