# Generated by Django 6.0.4 on 2026-04-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='documenttree',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_trees', to='clients.client'),
        ),
        migrations.AddField(
            model_name='documenttree',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='documents.clientfile'),
        ),
    ]
