# Generated by Django 6.0.4 on 2026-04-17 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('48hr_email', '48hr Email'), ('24hr_sms', '24hr SMS')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approval_item_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('approved', 'Approved'), ('sent', 'Sent'), ('skipped', 'Skipped')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeekStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_of', models.DateField(unique=True)),
                ('meetings_completed', models.IntegerField(default=0)),
                ('meetings_scheduled', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=15)),
                ('emails_approved', models.IntegerField(default=0)),
                ('emails_pending', models.IntegerField(default=0)),
                ('commission_close_week', models.BooleanField(default=False)),
                ('friday_off', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Week Stats',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('Discovery', 'Discovery'), ('LEAP Process', 'LEAP Process'), ('Implementation', 'Implementation'), ('Solera Heartbeat', 'Solera Heartbeat'), ('30-Day Check-In', '30-Day Check-In'), ('Other', 'Other')], max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_past', models.BooleanField(default=False)),
                ('transcript_text', models.TextField(blank=True)),
                ('leap_notes_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('teams_meeting_id', models.CharField(blank=True, max_length=100)),
                ('outlook_event_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clients.client')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
