# Generated by Django 6.0.4 on 2026-04-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
